### ISSUE TITLE
How to generate the training set?

### ISSUE THREAD

**Issue by Adenialzz** [mr-Mojo/NICER#4]
Hi, this paper is very interesting. You mentioned that the dataset was generated by the GIMP tool, I would like to know exactly how you batch generated the training set images. Can you offer some specific steps to generate the dataset? Thank you in advance.

**Comment by mr-Mojo** [comment]
Hi, thanks for reading our publication! 

For the batch-editing via GIMP, we created a batch script that loops through all files in a folder (train/test), and then applies an image filter with a given intensity. For the CAN in NICER, we use 8 filters (cf. publication): Contrast, Exposure, Brightness, ..., and enhance each image with min_filter and max_filter intensity.  

These intensities often range in [-200, +200]%, and sometimes even go to infinity. Most of these very high settings make the image unrecognizable, which is undesired in image enhancement. We hence used more conservative thresholds as min/max for the batch script and edited each image with +- 100% of the respective filter. 

For instructions on how to create a batch script for GIMP, cf. https://www.gimp.org/tutorials/Basic_Batch and read up on GIMP's script-fu API. When we did this, 2.10 just came out, idk what new features have been added since. Good luck! :)

**Comment by Adenialzz** [comment]
> Hi, thanks for reading our publication!
> 
> For the batch-editing via GIMP, we created a batch script that loops through all files in a folder (train/test), and then applies an image filter with a given intensity. For the CAN in NICER, we use 8 filters (cf. publication): Contrast, Exposure, Brightness, ..., and enhance each image with min_filter and max_filter intensity.
> 
> These intensities often range in [-200, +200]%, and sometimes even go to infinity. Most of these very high settings make the image unrecognizable, which is undesired in image enhancement. We hence used more conservative thresholds as min/max for the batch script and edited each image with +- 100% of the respective filter.
> 
> For instructions on how to create a batch script for GIMP, cf. https://www.gimp.org/tutorials/Basic_Batch and read up on GIMP's script-fu API. When we did this, 2.10 just came out, idk what new features have been added since. Good luck! :)

Thanks for your prompt and detailed reply, we are now able to do batch processing with David Batch Processing. In addition, we noticed that the enhancement effect of your demo is very good. Can you provide the code for training the CAN network if it is convenient?

**Comment by Adenialzz** [comment]
> 



> Hi, thanks for reading our publication!
> 
> For the batch-editing via GIMP, we created a batch script that loops through all files in a folder (train/test), and then applies an image filter with a given intensity. For the CAN in NICER, we use 8 filters (cf. publication): Contrast, Exposure, Brightness, ..., and enhance each image with min_filter and max_filter intensity.
> 
> These intensities often range in [-200, +200]%, and sometimes even go to infinity. Most of these very high settings make the image unrecognizable, which is undesired in image enhancement. We hence used more conservative thresholds as min/max for the batch script and edited each image with +- 100% of the respective filter.
> 
> For instructions on how to create a batch script for GIMP, cf. https://www.gimp.org/tutorials/Basic_Batch and read up on GIMP's script-fu API. When we did this, 2.10 just came out, idk what new features have been added since. Good luck! :)

Thanks for your prompt and detailed reply, we are now able to do batch processing images with DBP(David Batch Processing). In addition, we noticed that the enhancement effect of your demo is very good. Can you provide the code for training the CAN network if it is convenient?

**Comment by Adenialzz** [comment]
> Hi, thanks for reading our publication!
> 
> For the batch-editing via GIMP, we created a batch script that loops through all files in a folder (train/test), and then applies an image filter with a given intensity. For the CAN in NICER, we use 8 filters (cf. publication): Contrast, Exposure, Brightness, ..., and enhance each image with min_filter and max_filter intensity.
> 
> These intensities often range in [-200, +200]%, and sometimes even go to infinity. Most of these very high settings make the image unrecognizable, which is undesired in image enhancement. We hence used more conservative thresholds as min/max for the batch script and edited each image with +- 100% of the respective filter.
> 
> For instructions on how to create a batch script for GIMP, cf. https://www.gimp.org/tutorials/Basic_Batch and read up on GIMP's script-fu API. When we did this, 2.10 just came out, idk what new features have been added since. Good luck! :)

Thanks for your prompt and detailed reply, we are now able to do batch processing with DBP(David Batch Processing). In addition, we noticed that the enhancement effect of your demo is very good. Can you provide the code for training the CAN network if it is convenient?

**Comment by mr-Mojo** [comment]
I don't have access to the exact training routine that was used to train the CAN anymore, but you can find the CAN sourcecode in the models directory. Training the CAN was straightforward, though, I recall writing literally a one-to-one port of this tensorflow repository provided by the authors of the original paper: https://github.com/CQFIO/FastImageProcessing.

**Comment by Adenialzz** [comment]
> I don't have access to the exact training routine that was used to train the CAN anymore, but you can find the CAN sourcecode in the models directory. Training the CAN was straightforward, though, I recall writing literally a one-to-one port of this tensorflow repository provided by the authors of the original paper: https://github.com/CQFIO/FastImageProcessing.

Thank you for your patient answer. So your CAN network is actually trained using TensorFlow? I noticed that the model implementation and weight files in this repo are based on PyTorch. Or you mean that the training process of pytorch can be simply developed according to the tensorflow code (as you mentioned) given by the author of the original paper. I am Sorry that English is not my native language, so I don't really get what you mean by "one-to-one port".

**Comment by Adenialzz** [comment]
> 

The implementation of the can network itself is a simple fully convolutional network. What puzzles me is the two subsections "Parameterized operators" and "One network to represent them all" in the last section "Extensions" of "Fast image processing with FCN". And you mentioned in "NICER": 

> "During training, we apply one image operation per sample and let the CAN learn the relationship between the input and target output. At inference time, multiple image filters can be set, as the network interpolates correctly and applies the filters simultaneously."

May I ask how the eight additional channels representing the parameters are set during the training phase, will there be multiple operations applied to the training samples of an image simultaneously? We're trying to reproduce your work and make improvements and would appreciate some details from you. Thank you very much.

**Comment by mr-Mojo** [comment]
"One-to-one port" means that I took the Tensorflow code from that repository, and translated it into PyTorch. Regarding your second question: the training details are all in the Fast Image Processing paper and their repository. 

Basically, you prepend a one-hot vector that encodes the respective image filter (intensity then is +-1, ie, +-100%) to each pixel during training, ie, if your RGB is [0.2, 0.8, 0.8], and your filter is contrast (index 1), the network input for this pixel becomes [1.0, (0.0 x 7 for the other filters), 0.2, 0.8, 0.8]. Then, during inference time, you can arbitrarily combine the filters by setting the desired numbers in the intensity-vector you prepend. So during training, it's only 1 operation per sample, but during testing / inference, you can use several.

**Comment by Adenialzz** [comment]
> "One-to-one port" means that I took the Tensorflow code from that repository, and translated it into PyTorch. Regarding your second question: the training details are all in the Fast Image Processing paper and their repository. 
> 
> 
> 
> Basically, you prepend a one-hot vector that encodes the respective image filter (intensity then is +-1, ie, +-100%) to each pixel during training, ie, if your RGB is [0.2, 0.8, 0.8], and your filter is contrast (index 1), the network input for this pixel becomes [1.0, (0.0 x 7 for the other filters), 0.2, 0.8, 0.8]. Then, during inference time, you can arbitrarily combine the filters by setting the desired numbers in the intensity-vector you prepend. So during training, it's only 1 operation per sample, but during testing / inference, you can use several. 

Thanks again.
